routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OwnerController;
use App\Http\Controllers\OutletController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\OwnerOutletController;
use App\Http\Controllers\TransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Auth::routes();

Route::get('/', function () {
    return redirect()->route('login');
});
Route::get('/home', function () {
    return redirect()->route('histories');
})->name('home');

// routes/.php


Route::group(['middleware' => ['auth', 'permission']], function () {
    // Route::get('/dashboard', function () {
    //     return view('dashboard.index');
    // })->name('dashboard');
    
    Route::resource('users', UserController::class);
    Route::resource('outlets', OutletController::class);
    Route::resource('owners', OwnerController::class);
    
    Route::resource('roles', RoleController::class);
    Route::resource('permissions', PermissionController::class);
    
    Route::get('owner_outlets/{user_id}/form', [OwnerOutletController::class, 'form'])->name('owner_outlets.form');
    Route::put('owner_outlets/{user_id}', [OwnerOutletController::class, 'submit'])->name('owner_outlets.submit');

    Route::get('profile', [UserController::class, 'form'])->name('profile.form');
    Route::put('profile', [UserController::class, 'submit'])->name('profile.submit');

    Route::get('/transactions', [TransactionController::class, 'index'])->name('histories');
});

app/Models/Owner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Owner extends Model
{
    use HasFactory, SoftDeletes;


    protected $fillable = ['address', 'user_id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function transactions()
    {
        return $this->hasManyThrough(
            Transaction::class,
            Outlet::class,
            'id', // Foreign key pada tabel outlets
            'outlet_id', // Foreign key pada tabel transactions
            'user_id', // Lokal key pada tabel owners
            'id' // Lokal key pada tabel outlets
        );
    }

    
}

app/Http/Controllers/OwnerController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Owner;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class OwnerController extends Controller
{
    public function index()
    {
        $owners = Owner::all();
        return view('dashboard.owners.index', compact('owners'));
    }

    public function create()
    {
        return view('dashboard.owners.create');
    }

    public function store(Request $request)
    {
        // Validation rules
        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|min:8',
            'address' => 'required',
            'image' => 'max:2048', // Adjust this based on your requirements
        ]);

        // Create user
        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'image' => $request->image ?? null,

        ])->assignRole('owner');

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $path = $image->store('public/images/users');
            $imageUrl = Storage::url($path);
            $user->image = $imageUrl;
            $user->save();
        }

        // Create owner
        $user->owner()->create([
            'address' => $request->address,
        ]);

        return redirect()->route('owners.index')->with('success', 'Owner created successfully');
    }


    public function show(Owner $owner)
    {
        return view('dashboard.owners.show', compact('owner'));
    }

    public function edit(Owner $owner)
    {
        return view('dashboard.owners.edit', compact('owner'));
    }

    public function update(Request $request, Owner $owner)
    {
        $request->validate([
            'address' => 'required',
            'user_id' => 'nullable|exists:users,id',
            'image' => 'max:2048', // Adjust this based on your requirements
        ]);

        // Update owner details
        $owner->update([
            'address' => $request->address,
        ]);

        // Update user details
        $user = $owner->user;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = $request->password ? Hash::make($request->password) : $user->password;

        // Handle image update
        if ($request->hasFile('image')) {
            // Delete the old image if it exists
            if ($user->image) {
                $imageName = basename($user->image);
                Storage::delete('public/images/users/' . $imageName);
            }


            // Upload the new image
            $image = $request->file('image');
            $path = $image->store('public/images/users');
            $imageUrl = Storage::url($path);
            $user->image = $imageUrl;
        }

        $user->save();

        return redirect()->route('owners.index')->with('success', 'Owner updated successfully');
    }

    public function destroy(Owner $owner)
    {
        $owner->delete();

        return redirect()->route('owners.index')
            ->with('success', 'Owner deleted successfully');
    }

    public function profile_update(Request $request, Owner $owner)
    {
        $request->validate([
            'address' => 'required',
            'user_id' => 'nullable|exists:users,id',
            'image' => 'max:2048', // Adjust this based on your requirements
        ]);

        // Update owner details
        $owner->update([
            'address' => $request->address,
        ]);

        // Update user details
        $user = $owner->user;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = $request->password ? Hash::make($request->password) : $user->password;

        // Handle image update
        if ($request->hasFile('image')) {
            // Delete the old image if it exists
            if ($user->image) {
                $imageName = basename($user->image);
                Storage::delete('public/images/users/' . $imageName);
            }


            // Upload the new image
            $image = $request->file('image');
            $path = $image->store('public/images/users');
            $imageUrl = Storage::url($path);
            $user->image = $imageUrl;
        }

        $user->save();

        return redirect()->route('owners.index')->with('success', 'Owner updated successfully');
    }
}

resources/views/dashboard/owners/create.blade.php
@php
    $title = 'Owner'
@endphp
@extends('layouts.dashboard.app')
@section('title', $title ?? '')
@section('content')
    <!-- BEGIN breadcrumb -->
    {{-- <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:;">Page Options</a></li>
        <li class="breadcrumb-item active">Blank Page</li>
    </ol>
    <!-- END breadcrumb -->
    <!-- BEGIN page-header -->
    <h1 class="page-header">Blank Page <small>header small text goes here...</small></h1>
    <!-- END page-header -->
    <!-- BEGIN panel --> --}}
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h4 class="panel-title">{{ $title ?? '' }}</h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-default" data-toggle="panel-expand"><i
                        class="fa fa-expand"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-success" data-toggle="panel-reload"><i
                        class="fa fa-redo"></i></a>
            
            </div>
        </div>
        <div class="panel-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form action="{{ route('owners.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name"
                        name="name" value="{{ old('name') }}" required>
                    @error('name')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control @error('email') is-invalid @enderror" id="email"
                        name="email" value="{{ old('email') }}" required>
                    @error('email')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control @error('password') is-invalid @enderror" id="password"
                        name="password" required>
                    @error('password')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="image" class="form-label">Image</label>
                    <input type="file" class="form-control @error('image') is-invalid @enderror" id="image"
                        name="image">
                    @error('image')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
             
                <div class="mb-3">
                    <label for="address" class="form-label">Address</label>
                    <input type="text" class="form-control @error('address') is-invalid @enderror" id="address"
                        name="address" value="{{ old('address') }}" required>
                    @error('address')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
             

                <button type="submit" class="btn btn-primary">Create</button>
                <a href="{{ route('owners.index') }}" class="btn btn-default">Cancel</a>
            </form>

        </div>
    </div>
    <!-- END panel -->
@endsection

resources/views/dashboard/owners/edit.blade.php
@php
    $title = 'Owner';
@endphp
@extends('layouts.dashboard.app')
@section('title', $title ?? '')
@section('content')
    <!-- BEGIN breadcrumb -->
    {{-- <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:;">Page Options</a></li>
        <li class="breadcrumb-item active">Blank Page</li>
    </ol>
    <!-- END breadcrumb -->
    <!-- BEGIN page-header -->
    <h1 class="page-header">Blank Page <small>header small text goes here...</small></h1>
    <!-- END page-header -->
    <!-- BEGIN panel --> --}}
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h4 class="panel-title">{{ $title ?? '' }}</h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-default" data-toggle="panel-expand"><i
                        class="fa fa-expand"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-success" data-toggle="panel-reload"><i
                        class="fa fa-redo"></i></a>

            </div>
        </div>
        <div class="panel-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form action="{{ route('owners.update', $owner) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')



                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name"
                        name="name" value="{{ old('name', $owner->user->name) }}" required>
                    @error('name')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control @error('email') is-invalid @enderror" id="email"
                        name="email" value="{{ old('email', $owner->user->email) }}" required>
                    @error('email')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control @error('password') is-invalid @enderror" id="password"
                        name="password">
                    @error('password')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="image" class="form-label">Image</label>
                    <input type="file" class="form-control @error('image') is-invalid @enderror" id="image"
                        name="image">
                    @error('image')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                    @if ($owner->user->image)
                        <div class="mt-2">
                            <img src="{{ asset($owner->user->image) }}" alt="User Image" class="img-thumbnail"
                                style="max-width: 100px;">
                        </div>
                    @endif
                </div>

                <div class="mb-3">
                    <label for="address" class="form-label">Address</label>
                    <input type="text" class="form-control @error('address') is-invalid @enderror" id="address"
                        name="address" value="{{ old('address', $owner->address) }}" required>
                    @error('address')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>


                <button type="submit" class="btn btn-primary">Update</button>
                <a href="{{ route('owners.index') }}" class="btn btn-default">Cancel</a>
            </form>

        </div>
    </div>
    <!-- END panel -->
@endsection

resources/views/dashboard/owners/index.blade.php
@php
    $title = 'Owner';
@endphp
@extends('layouts.dashboard.app')
@section('title', $title ?? '')
@section('content')
    <!-- BEGIN breadcrumb -->
    {{-- <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:;">Page Options</a></li>
        <li class="breadcrumb-item active">Blank Page</li>
    </ol>
    <!-- END breadcrumb -->
    <!-- BEGIN page-header -->
    <h1 class="page-header">Blank Page <small>header small text goes here...</small></h1>
    <!-- END page-header -->
    <!-- BEGIN panel --> --}}
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h4 class="panel-title">{{ $title ?? '' }}</h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-default" data-toggle="panel-expand"><i
                        class="fa fa-expand"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-success" data-toggle="panel-reload"><i
                        class="fa fa-redo"></i></a>
                
                <a href="{{ route('owners.create') }}" class="btn btn-xs btn-primary">Add</a>
            </div>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Image</th>
                            <th>Address</th>
                            <th>Nama</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($owners as $owner)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>
                                    @if ($owner->user->image)
                                        <img src="{{ asset($owner->user->image) }}" alt="owner Image" class="img-thumbnail"
                                            style="max-width: 100px;">
                                    @else
                                        No Image
                                    @endif
                                </td>
                                <td>{{ $owner->address }}</td>
                                <td>{{ $owner->user->name }}</td>
                                <td>
                                    <a href="{{ route('owners.edit', $owner) }}" class="btn btn-primary btn-sm">Edit</a>
                                    <a href="{{ route('owner_outlets.form', $owner->user->id) }}"
                                        class="btn btn-success btn-sm">Outlet</a>
                                    <form action="{{ route('owners.destroy', $owner) }}" method="POST" class="d-inline">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-sm"
                                            onclick="return confirm('Are you sure you want to delete this owner?')">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div>
    <!-- END panel -->
@endsection